
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const CompetitiveAnalysis = lazy(() => import("./pages/CompetitiveAnalysis.tsx"));
const PricingRecommendations = lazy(() => import("./pages/PricingRecommendations.tsx"));
const Scraping = lazy(() => import("./pages/Scraping.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/competitive-analysis", element: <UserGuard><CompetitiveAnalysis /></UserGuard>},
	{ path: "/competitiveanalysis", element: <UserGuard><CompetitiveAnalysis /></UserGuard>},
	{ path: "/pricing-recommendations", element: <UserGuard><PricingRecommendations /></UserGuard>},
	{ path: "/pricingrecommendations", element: <UserGuard><PricingRecommendations /></UserGuard>},
	{ path: "/scraping", element: <UserGuard><Scraping /></UserGuard>},

];
